### ISSUE TITLE
DB 테이블 설계 URL 끊긴 것 같음

### ISSUE THREAD

**Issue by viiviii** [olivejua/simplelog#12]
노션 회의록에 추가되어있는 DB(테이블) 설계 URL 들어가보면
10월 1일 유료화 공지 뜨면서 더이상 접속 불가능한데 다들 잘 뜨시나요?

추가) 더불어 엔티티 연관관계 다이어그램 링크도 확인 부탁🙋🏼‍♀️

**Comment by olivejua** [comment]
이메일로 공유했습니다!
