### ISSUE TITLE
.gitignore에 local-db.yml 추가

### ISSUE THREAD

**Issue by viiviii** [olivejua/simplelog#13]
여러분🙋🏼‍♀️ `.gitignore`에 아래 파일도 추가해도 되겠읍니까?

```yml
application-local-db.yml
```

### 이유
- .gitignore 목록이 일관성이 있어보이고
- local을 real이란 이름으로 갖고있으려니 개발 시 흥이 안남

**Comment by olivejua** [comment]
그럼 `application-db.yml` 로 통일하는건 어떠십니까? (기존 파일명 변경: `application-real-db.yml` -> `application-db.yml`

 db 설정파일이 각 역할별로 분리되어야하거나 여러db를 동시에 사용해야할 경우 파일명을 여러개로 나눠질 수 있는데 저희는 아직 간단하니까 파일명을 다르게 설정하지 않는것이 좋지 않을까욥?

**Comment by viiviii** [comment]
난 좋와

**Comment by olivejua** [comment]
@viiviii 그럼 `.gitignore`와 서버에 있는 db 파일명도 변경해놓을게!

**Comment by olivejua** [comment]
엇.. 설정파일 변경을 안했네요.... 뒤늦게 수정합니다
