### ISSUE TITLE
ssh simplelog 연결 시도 시 timed out 발생

### ISSUE THREAD

**Issue by viiviii** [olivejua/simplelog#15]
저는 시간 초과로 연결 안돼서 다른 카페나 집에서도 해봤는데도 동일해요🥲
혹시 두 분은 잘 되시는지 궁금합니다

### 로그
```
ssh: connect to host 52.79.78.10 port 22: Operation timed out
```

### config
<img width="468" alt="스크린샷 2021-11-07 오후 2 14 18" src="https://user-images.githubusercontent.com/75404713/140633250-05951007-acce-47c6-87d9-fa3ceedeb2a8.png">

**Comment by viiviii** [comment]
@miyeunlee @olivejua

**Comment by olivejua** [comment]
아직 접속해도 그대로인가요?

저도 똑같은 메시지가 나왔습니다. 그래서 서버를 재부팅하고 아래 링크대로 접속 했더니 접근 가능했고, 
연결 종료 후 다시 원래의 방식대로 하니 되네요!
```
user@localhost:~$ ssh -v -i simplelog-master.pem ec2-user@52.79.78.10
```

```
ssh simplelog
```


다음에 또 이러한 문제가 생기면 아래 방법대로 시도해서 추적해봐야겠네요!
https://aws.amazon.com/ko/premiumsupport/knowledge-center/ec2-linux-ssh-troubleshooting/
https://aws.amazon.com/ko/premiumsupport/knowledge-center/ec2-linux-resolve-ssh-connection-errors/

**Comment by viiviii** [comment]
이제 저도 잘 접속됩니다! 인스턴스 상태 검사도 이제 2개 다 통과 됐네요😊
제가 확인할 때는 1개만 통과되어 있었는데 상태 검사를 다 통과하지 못했을 때도 연결 문제가 발생하는 것 같아요!

[Common causes for connection issues](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/TroubleshootingInstancesConnecting.html#TroubleshootingInstancesCommonCauses)


![image](https://user-images.githubusercontent.com/75404713/141243753-c5a088dc-507b-4d2c-80a8-b5168dea2f9a.png)
