### ISSUE TITLE
RestDocs html 생성시 build fail 문제가 있음 (해결)

### ISSUE THREAD

**Issue by olivejua** [olivejua/simplelog#17]
연관 이슈 : #11 

RestDocs를 사용하여 API를 만드려면 먼저 `*.adoc` 파일을 생성하고, 이 파일을 `*.html` 로 만들어주어 API 문서가 만들어집니다.

하지만 이 과정에서 build fail이 되었고, 메시지는 아래와 같이 나왔습니다.
<img width="1034" alt="스크린샷 2021-11-13 오후 4 11 31" src="https://user-images.githubusercontent.com/45840556/141609691-4ea8cc7e-e3a7-4d17-adfe-4f1a20642ab1.png">

구글링 해보니 Gradle 7버전 이상과 저희 프로젝트 build.gralde 파일 내에 있던 플러그인이 호환되지 않아서였더라고요.
```build.gradle
plugins {
   ...
    id 'org.asciidoctor.convert' version '1.5.8'
    ...
}
```
simplelog Gradle 버전: 7.0.2

(출처: https://stackoverflow.com/questions/68539790/configuring-asciidoctor-when-using-spring-restdoc)

해결방법은 Gradle 버전을 6.* 버전으로 낮추거나 플러그인을 jvm.convert 로 변경하는 것이었습니다. 제가 선택한 방법은 후자입니다.

하지만 변경하면 이런에러가 또 뜸...
```
A problem occurred evaluating root project 'backend'.
> Could not find method asciidoctor() for arguments [org.springframework.restdocs:spring-restdocs-asciidoctor:2.0.4.RELEASE] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

그래서 아래와 같이 수정했더니 빌드 SUCCESS 됐음...

``` build.gradle
plugins {
	id 'org.springframework.boot' version '2.5.0'
	id 'io.spring.dependency-management' version '1.0.11.RELEASE'
	id 'java'
	id 'com.ewerk.gradle.plugins.querydsl' version '1.0.10'
	**(변경) id "org.asciidoctor.convert" version "1.5.9.2"  --> id 'org.asciidoctor.jvm.convert' version '3.3.2' **
}

group = 'com.simplelog'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

**(추가)
configurations {
	asciidoctorExtensions
}
**

ext {
	snippetsDir = file('build/generated-snippets')
}

repositories {
	mavenCentral()
}

dependencies {
	...
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	**(변경) asciidoctor --> asciidoctorExtensions ** 'org.springframework.restdocs:spring-restdocs-asciidoctor'
	testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
}

test {
	useJUnitPlatform()
	outputs.dir snippetsDir
}

asciidoctor {
        **(추가) configurations 'asciidoctorExtensions' **
	inputs.dir snippetsDir
	dependsOn test
}

bootJar {
	dependsOn asciidoctor
**(변경)
	from ("${asciidoctor.outputDir}/html5") {
		into 'static/docs'
	}

       -->

       copy {
		from "${asciidoctor.outputDir}"
		into 'src/main/resources/static/docs'
	}
**
}

...

```

구글링해보니 `jvm.converter` 는 기본으로 `asciidoctor` configuration을 생성해주지 않아서 명시적으로 task asciidoctor에 추가해줘야한대요.
참고링크 : https://github.com/spring-projects/spring-restdocs/issues/680#issuecomment-618228576

공식문서대로 설정해도 gradle 7버전 이상 쓰면 실패하는 듯여..
코드 참고는 아래 링크를 봤습니당
https://github.com/spring-projects/spring-restdocs/issues/680

**Comment by viiviii** [comment]
어이구 고생했네요🥲정보 공유 고마워오!!!!👏👏

**Comment by miyeunlee** [comment]
에러 해결하시고 정리까지 해주시다니..👍 수고 많으셨습니다!
