### ISSUE TITLE
이미지 데이터 저장하는 방법 이렇게 하는 건 어떤가요?

### ISSUE THREAD

**Issue by olivejua** [olivejua/simplelog#19]
현재 이미지 저장이 필요한 곳은 
User - 프로필 이미지 (0..1개)
Post - 첨부이미지 (0..N개)

총 2곳입니다.

여기서 DB에 파일 테이블 한곳에서 두개의 도메인 사진을 관리하는 것도 생각해봤는데 (현재 회사에서 이런식으로 사용중입니다 ㅎㅎ) 장단점을 정리해보니 이렇습니다.
장점
- DB 관계가 좀 더 단순해진다.
- 한곳에서 관리를 하니 이해하기가 쉽다.

단점
- DB 상 연관관계를 엮기가 힘들다. (FK로 묶기가 애매해짐, 고로 일관성이 떨어질 수 있음)
- 데이터가 많아지면 검색하지 않아도 될 데이터까지 검색하느라 오래걸릴 수 있다.

다른 곳에서는 파일관리를 어떻게 하는지 궁금해 깃헙 레파지토리들을 검색해본 결과 Url 형태(문자열)로 저장을 많이 하더라고요. 

제가 생각한 파일 저장 방법은 
User: `profileUrl` 컬럼 추가 (데이터: S3 링크 경로)
-> 1:1 관계이기 때문에 컬럼만 추가했을 때 별도의 join문으로 다른 테이블 검색해볼 필요없이 해당 User 조회만 하면 되니 단순해질 것으로 생각했습니다.
Post:  `PostImage` 테이블 추가 [컬럼들: `postId`(FK), `imageUrl`(데이터: S3 링크 경로)]
-> 1:N 관계이기 때문에 Url을 User처럼 한곳에서 관리하면 문자열이 길어져 한눈에 알아보기 힘들 것 같아 Post를 키로 묶고, url을 연결시키는 방법으로 생각했습니다.

혹시 다른 의견이 있다면 말씀해주세요! ㅎㅎ

**Comment by viiviii** [comment]
좋아요!🎉

**Comment by olivejua** [comment]
구현 완료했으니 이슈 닫겠습니다!
