### ISSUE TITLE
Git Submodule과 Github actions 적용하기 (+사용법, 구현 내용 정리)

### ISSUE THREAD

**Issue by olivejua** [olivejua/simplelog#21]
##  목표
- 계정이 담겨있는 `보안파일`들을 public 하지 않은 곳에서 관리하면서 git 소스코드에 적용시킨다.
- 소스코드를 Git에 올리면 통합하여 `build`, `test`까지 하는 과정을 자동화한다.

## 내용
`simplelog` respository는 현재 프로젝트 구동시 반드시 필요한 계정정보와 앱 속성들을 담고 있는 `보안파일`이 포함되어 있지 않습니다.
이대로 build을 하게 되면 build 실패를 합니다.

제가 처음 시도했던 방법은 `gpg`를 이용해서 보안파일을 암호화를 하고 암호화한 `Key파일`을 각 팀원들과 서버에 공유하여 빌드시에 적용할 수 있도록 하는 것이었습니다.
근데 여기서 주저하게 되었던 점은 관리해야하는 `Key파일`이 생긴다는 점과 빌드시에 복호화하는 번거로움을 한번 더 거쳐야했습니다.

몇번의 구글링 끝에 우연히 우아한 테크캠프에서 프로젝트를 진행한 블로그를 보게되었고, `Git submodule`을 사용하여 이 문제를 해결했다는 것을 알게되었습니다. 구현방법도 쉽고 암호화 등 따로 할 필요가 없어 프로젝트 진행도 쉽게 할 수 있어보였습니다. 

### submodule 적용
_(메인 프로젝트: `public repository` /  서브 프로젝트: `private repository`)_

- `보안파일`을 보관하고 관리할 서브 프로젝트 생성
- 서브프로젝트로 `보안파일` 업로드
- 메인프로젝트에 서브 프로젝트를 서브모듈로 추가 
   - command: git submodule add https://github.com/simplelog-secret/simplelog-secret.git ./secret
-  root 디렉토리에 `.gitmodules` 파일과 `secret`폴더가 생성된 것을 확인
- 메인프로젝트에 생성된 파일들을 push

### github actions 적용
- Repository내 Actions 탭에서 `java with Gradle` 요소의 `setup this workflow` 클릭 
- yml workflow 설정파일 생성
   -  반드시 `.github`/`workflow`/`*.yml` 에 위치하고 있어야함
- build시 submodule에 있는 보안 파일들을 적절한 위치로 복사해놓는 `Gradle Task` 추가
   ``` build.gradle
   ...
   processResources.dependsOn('copySecret')
   
   task copySecret(type: Copy) {
   	copy {
   		from 'secret'
   		include '*.yml'
   		into 'src/main/resources'
   	}

   	copy {
   		from 'secret/application-aws.yml'
   		into 'src/test/resources'
    	}
   }
   ...
   ```

- [Personal Access Token 발급](https://docs.github.com/en/actions/security-guides/encrypted-secrets)
- [Repository의 Secrets를 이용해 이 Token을 등록](https://docs.github.com/en/actions/security-guides/encrypted-secrets)
- workflow/*.yml 파일에 submodule 설정 추가
   ``` ./.github/workflow/github-actions.yml
   ...
   with:
        submodules: true
        token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}
   ...
   ```

## 팀원이 submodule 적용하기 
`submodule`이라는게 프로젝트 안에 따로 `git`으로 관리하는 작은 프로젝트 하나가 더 있다고 생각하면 됩니다! 

#### 처음 submodule을 적용할 때
- command: git submodule init 
   - `.gitmodules` 라는 파일이 생성됨
- command: git submodule update
   - clone submodule project
- command: git submodule foreach git checkout main
   - submodule project의 main 브랜치로 checkout

#### private project의 보안파일을 업데이트해야할 때

여기서 중요한 점은 서브 프로젝트에서 수정을 한다면  **서브 프로젝트 먼저 commit 한 뒤 메인 프로젝트를 commit 해야합니다.**
메인프로젝트는 commit시 자신에게 포함되어 있는 서브프로젝트의 최근 commit 내용까지만 포함하여 commit이 되어 버리기 때문에 그 후에 submodule에 업데이트가 되어도 메인프로젝트에 적용이 되지 않습니다.

- 먼저 `secret` 디렉토리로 이동
- command: git checkout main
- command: git pull
- {{업데이트 작업}}
- command: git add .
- command: git commit -m 'commit message'
- command: git push 

####  선 서브 후 메인 자동 설정하기
command 창에서 git commit 을 한다면 이러한 실수(서브 커밋전에 메인을 커밋한다거나...) 를 막기위해 아래와 같은 설정을 하면 자동으로 push 전에 submodule의 변경사항을 체크해주니 좋다고 합니다!

- command: git config push.recurseSubmodules check  (submodule이 모두 push된 상태여야지만 메인을 push함)
- command: git config push.recurseSubmodules on-demand (submodule 변경사항 모두 push하고, 성공하면 메인을 push함)

* * *
### 참고 
- [jujeol-jujeol 블로그](https://jujeol-jujeol.github.io/2021/07/12/git-submodule-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0/)
- [zzsza 블로그](https://zzsza.github.io/development/2020/06/06/github-action/)

**Comment by viiviii** [comment]
### 프로젝트 빌드 시
gradle.build을 한번 reload 시켜서 `copySecret` task를 실행시켜 줬습니다

### SSH를 사용할 경우
저는 SSH 방식을 사용하고 있어 **처음 submodule을 적용할 때** 부분에서
아래 명령어로 URL 설정 변경 후 submodule update를 진행했습니다

```
git config submodule.secret.url {_git_서브모듈_ssh_url_}
```
참고링크: [Git-도구-서브모듈#서브모듈 시작하기의 노트 섹션](https://git-scm.com/book/ko/v2/Git-%EB%8F%84%EA%B5%AC-%EC%84%9C%EB%B8%8C%EB%AA%A8%EB%93%88#_%EC%84%9C%EB%B8%8C%EB%AA%A8%EB%93%88_%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0)

**Comment by viiviii** [comment]
_추가 설명:_ 
```
git submodule foreach git checkout main
```
위 명령어의 사용 이유를 좀 더 알아보면
* `foreach` - 한번에 각 서브 모듈에 git 명령을 내리는 명령
   * 한 프로젝트에 다수의 서브모듈이 포함된 경우 유용
   * 다른 사용 예: `git submodule foreach 'git diff'` - 모든 서브모듈의 diff 내용 확인

그렇다면 왜 모든 서브모듈을 main 브랜치로 체크아웃 하는 것일까?
* `git submodule update`를 실행하면 서브 모듈 로컬 저장소는 `Detached HEAD` 상태로 남음
* `Detached` 상태라는건 변경 내용을 추적하는 로컬 브랜치(ex: main, master)가 없다는 것이므로 [브랜치 없이 서브모듈에서 수정 작업을 하다가 `git submodule update`를 실행하면 작업 내용을 잃어버릴 수 있음](https://git-scm.com/book/ko/v2/Git-%EB%8F%84%EA%B5%AC-%EC%84%9C%EB%B8%8C%EB%AA%A8%EB%93%88#_%EC%84%9C%EB%B8%8C%EB%AA%A8%EB%93%88_%EA%B4%80%EB%A6%AC%ED%95%98%EA%B8%B0)
* 그래서 서브모듈이 브랜치를 추적하게 하기 위해 checkout을 진행

![image](https://user-images.githubusercontent.com/75404713/145164595-19f95a34-8021-463f-9b8d-fbb8276a4e0b.png)

_+ 추가로 궁금할까봐_
HEAD에는 attached와 detached 2가지 state가 있는데
  * `attached`: HEAD가 브랜치를 가르킴(우리가 항상 보는 것)
  * `detached`: HEAD가 커밋을 가르킴
